services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DEFAULT_BUCKETS: mybucket1
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - minionetwork
volumes:
  minio_data: {}
networks:
  minionetwork:
    driver: bridge